language: ruby
rvm:
- 2.6.3
services:
- postgresql
script:
- bundle install
- bin/rails db:create
- bin/rails db:migrate
- bundle exec rspec
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
  app: HappyChappy
  on:
    repo: Sumeet-Raina/HappyChappy
  run:
  - rake db:migrate
  - restart
